source 'https://rubygems.org'
 
 gem 'ruby-progressbar'
 gem 'rails_semantic_logger'
 gem 'json'
 gem 'rubyzip'
 # gem 'builder'
 gem 'pdfkit'
 gem 'configatron'
 gem 'restclient'
 gem 'unirest'
 gem 'highline'
 gem 'prawn'
 gem 'prawn-table'
